apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-dec7-eswar
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet-dec7-eswar
    spec:
      containers:
      - name: dotnet-dec7-eswar
        image: adityaregistry.azurecr.io/eswarpullagan/myapache2-code-eswar:#{Build.BuildId}#
        ports:
        - name: codeport
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-dec7-eswar
spec:
  ports:
  - port: 8888
    nodePort: 31112
    targetPort: codeport
    protocol: TCP
  selector:
    app: dotnet-dec7-eswar
  type: LoadBalancer
